-- PACKAGE SPECIFICATION
CREATE
OR REPLACE PACKAGE PKG_PHARMACY_SYSTEM AS
-- Patient operations
PROCEDURE ADD_PATIENT (
    P_FIRST_NAME IN PATIENT.FIRST_NAME,
    P_LAST_NAME IN PATIENT.LAST_NAME,
    P_PHONE IN PATIENT.PHONE,
    P_EMAIL IN PATIENT.EMAIL,
    P_BIRTH_DATE IN PATIENT.BIRTH_DATE,
    P_GENDER IN PATIENT.GENDER,
    P_ADDRESS IN PATIENT.ADDRESS
);

PROCEDURE UPDATE_PATIENT (
    P_PATIENT_ID IN PATIENT.PATIENT_ID,
    P_FIRST_NAME IN PATIENT.FIRST_NAME,
    P_LAST_NAME IN PATIENT.LAST_NAME,
    P_PHONE IN PATIENT.PHONE,
    P_EMAIL IN PATIENT.EMAIL,
    P_BIRTH_DATE IN PATIENT.BIRTH_DATE,
    P_GENDER IN PATIENT.GENDER,
    P_ADDRESS IN PATIENT.ADDRESS
);

PROCEDURE DELETE_PATIENT (P_PATIENT_ID IN PATIENT.PATIENT_ID);

-- Medicine operations
PROCEDURE ADD_MEDICINE (
    P_CATEGORY_ID IN MEDICINE.CATEGORY_ID,
    P_MEDICINE_NAME IN MEDICINE.MEDICINE_NAME,
    P_DOSAGE_FORM IN MEDICINE.DOSAGE_FORM,
    P_STRENGTH IN MEDICINE.STRENGTH,
    P_UNIT_PRICE IN MEDICINE.UNIT_PRICE,
    P_REQUIRES_PRESCRIPTION IN MEDICINE.REQUIRES_PRESCRIPTION
);

PROCEDURE UPDATE_MEDICINE (
    P_MEDICINE_ID IN MEDICINE.MEDICINE_ID,
    P_CATEGORY_ID IN MEDICINE.CATEGORY_ID,
    P_MEDICINE_NAME IN MEDICINE.MEDICINE_NAME,
    P_DOSAGE_FORM IN MEDICINE.DOSAGE_FORM,
    P_STRENGTH IN MEDICINE.STRENGTH,
    P_UNIT_PRICE IN MEDICINE.UNIT_PRICE,
    P_REQUIRES_PRESCRIPTION IN MEDICINE.REQUIRES_PRESCRIPTION
);

PROCEDURE DELETE_MEDICINE (P_MEDICINE_ID IN MEDICINE.MEDICINE_ID);

-- Sale operations
PROCEDURE CREATE_SALE (
    P_PHARMACY_ID IN SALE.PHARMACY_ID,
    P_PATIENT_ID IN SALE.PATIENT_ID,
    P_PRESCRIPTION_ID IN SALE.PRESCRIPTION_ID,
    P_SALE_DATE IN SALE.SALE_DATE,
    P_STATUS IN SALE.STATUS,
    P_SALE_ID OUT SALE.SALE_ID
);

PROCEDURE ADD_SALE_ITEM (
    P_SALE_ID IN SALE_ITEM.SALE_ID,
    P_BATCH_ID IN SALE_ITEM.BATCH_ID,
    P_QUANTITY IN SALE_ITEM.QUANTITY,
    P_UNIT_PRICE IN SALE_ITEM.UNIT_PRICE
);

PROCEDURE ADD_PAYMENT (
    P_SALE_ID IN PAYMENT.SALE_ID,
    P_PAYMENT_METHOD_ID IN PAYMENT.PAYMENT_METHOD_ID,
    P_AMOUNT IN PAYMENT.AMOUNT,
    P_PAYMENT_DATE IN PAYMENT.PAYMENT_DATE,
    P_PAYMENT_STATUS IN PAYMENT.PAYMENT_STATUS
);

-- Report operations
-- using optional parameters for dynamic filtering.
PROCEDURE GET_SALES_REPORT (
    P_START_DATE IN SALE.SALE_DATE DEFAULT NULL,
    P_END_DATE IN SALE.SALE_DATE DEFAULT NULL,
    P_PHARMACY_ID IN SALE.PHARMACY_ID DEFAULT NULL,
    P_STATUS IN SALE.STATUS DEFAULT NULL
);

PROCEDURE GET_LOW_STOCK_REPORT (
    P_PHARMACY_ID IN MEDICINE_BATCH.PHARMACY_ID DEFAULT NULL,
    P_MIN_QUANTITY IN MEDICINE_BATCH.CURRENT_QUANTITY DEFAULT 10
);

PROCEDURE GET_PRESCRIPTION_REPORT (
    P_PATIENT_ID IN PRESCRIPTION.PATIENT_ID DEFAULT NULL,
    P_DOCTOR_ID IN PRESCRIPTION.DOCTOR_ID DEFAULT NULL,
    P_STATUS IN PRESCRIPTION.STATUS DEFAULT NULL
);

-- Duplicate cleanup operation
PROCEDURE REMOVE_DUPLICATE_PATIENTS;

END PKG_PHARMACY_SYSTEM;

/