--- Patient
CREATE TABLE
    patient (
        patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name VARCHAR2 (50) NOT NULL,
        last_name VARCHAR2 (50) NOT NULL,
        phone VARCHAR2 (20),
        email VARCHAR2 (100),
        birth_date DATE,
        gender VARCHAR2 (10),
        address VARCHAR2 (200),
        CONSTRAINT uk_patient_email UNIQUE (email),
        CONSTRAINT chk_patient_gender CHECK (gender IN ('Male', 'Female', 'Other'))
    );

--- Doctor
CREATE TABLE
    doctor (
        doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name VARCHAR2 (50) NOT NULL,
        last_name VARCHAR2 (50) NOT NULL,
        specialization VARCHAR2 (100),
        phone VARCHAR2 (20),
        email VARCHAR2 (100),
        license_no VARCHAR2 (50),
        CONSTRAINT uk_doctor_email UNIQUE (email),
        CONSTRAINT uk_doctor_license UNIQUE (license_no)
    );

--- Pharmacy
CREATE TABLE
    pharmacy (
        pharmacy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pharmacy_name VARCHAR2 (100) NOT NULL,
        phone VARCHAR2 (20),
        email VARCHAR2 (100),
        address VARCHAR2 (200),
        city VARCHAR2 (50),
        CONSTRAINT uk_pharmacy_email UNIQUE (email)
    );

--- Supplier
CREATE TABLE
    supplier (
        supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier_name VARCHAR2 (100) NOT NULL,
        contact_person VARCHAR2 (100),
        phone VARCHAR2 (20),
        email VARCHAR2 (100),
        address VARCHAR2 (200),
        city VARCHAR2 (50),
        CONSTRAINT uk_supplier_email UNIQUE (email)
    );

--- Medicine Category
CREATE TABLE
    medicine_category (
        category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_name VARCHAR2 (100) NOT NULL,
        description VARCHAR2 (250),
        CONSTRAINT uk_category_name UNIQUE (category_name)
    );

--- Medicine
CREATE TABLE
    medicine (
        medicine_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_id NUMBER NOT NULL,
        medicine_name VARCHAR2 (100) NOT NULL,
        dosage_form VARCHAR2 (50) NOT NULL,
        strength VARCHAR2 (50),
        unit_price NUMBER (10, 2) NOT NULL,
        requires_prescription CHAR(1) NOT NULL,
        CONSTRAINT fk_medicine_category FOREIGN KEY (category_id) REFERENCES medicine_category (category_id),
        CONSTRAINT chk_medicine_price CHECK (unit_price >= 0),
        CONSTRAINT chk_requires_prescription CHECK (requires_prescription IN ('Y', 'N'))
    );

--- Medicine Batch
CREATE TABLE
    medicine_batch (
        batch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        medicine_id NUMBER NOT NULL,
        supplier_id NUMBER NOT NULL,
        pharmacy_id NUMBER NOT NULL,
        batch_number VARCHAR2 (50) NOT NULL,
        purchase_price NUMBER (10, 2) NOT NULL,
        current_quantity NUMBER NOT NULL,
        expiration_date DATE NOT NULL,
        received_date DATE NOT NULL,
        CONSTRAINT fk_batch_medicine FOREIGN KEY (medicine_id) REFERENCES medicine (medicine_id),
        CONSTRAINT fk_batch_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id),
        CONSTRAINT fk_batch_pharmacy FOREIGN KEY (pharmacy_id) REFERENCES pharmacy (pharmacy_id),
        CONSTRAINT uk_batch_unique UNIQUE (medicine_id, pharmacy_id, batch_number),
        CONSTRAINT chk_batch_purchase_price CHECK (purchase_price >= 0),
        CONSTRAINT chk_batch_current_quantity CHECK (current_quantity >= 0),
        CONSTRAINT chk_batch_dates CHECK (expiration_date > received_date)
    );

--- Prescription
CREATE TABLE
    prescription (
        prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        patient_id NUMBER NOT NULL,
        doctor_id NUMBER NOT NULL,
        prescription_date DATE NOT NULL,
        diagnosis VARCHAR2 (250),
        status VARCHAR2 (20) NOT NULL,
        CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id),
        CONSTRAINT fk_prescription_doctor FOREIGN KEY (doctor_id) REFERENCES doctor (doctor_id),
        CONSTRAINT chk_prescription_status CHECK (
            status IN ('ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED')
        )
    );

--- Prescription Item
CREATE TABLE
    prescription_item (
        prescription_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        prescription_id NUMBER NOT NULL,
        medicine_id NUMBER NOT NULL,
        quantity NUMBER NOT NULL,
        dosage_instruction VARCHAR2 (250),
        duration_days NUMBER,
        CONSTRAINT fk_pres_item_prescription FOREIGN KEY (prescription_id) REFERENCES prescription (prescription_id),
        CONSTRAINT fk_pres_item_medicine FOREIGN KEY (medicine_id) REFERENCES medicine (medicine_id),
        CONSTRAINT chk_pres_item_quantity CHECK (quantity > 0),
        CONSTRAINT chk_pres_item_duration CHECK (
            duration_days IS NULL
            OR duration_days > 0
        )
    );

--- Sale
CREATE TABLE
    sale (
        sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pharmacy_id NUMBER NOT NULL,
        patient_id NUMBER,
        prescription_id NUMBER,
        sale_date DATE NOT NULL,
        status VARCHAR2 (20) NOT NULL,
        CONSTRAINT fk_sale_pharmacy FOREIGN KEY (pharmacy_id) REFERENCES pharmacy (pharmacy_id),
        CONSTRAINT fk_sale_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id),
        CONSTRAINT fk_sale_prescription FOREIGN KEY (prescription_id) REFERENCES prescription (prescription_id),
        CONSTRAINT chk_sale_status CHECK (status IN ('COMPLETED', 'CANCELLED', 'REFUNDED'))
    );

--- Sale Item
CREATE TABLE
    sale_item (
        sale_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_id NUMBER NOT NULL,
        batch_id NUMBER NOT NULL,
        quantity NUMBER NOT NULL,
        unit_price NUMBER (10, 2) NOT NULL,
        CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) REFERENCES sale (sale_id),
        CONSTRAINT fk_sale_item_batch FOREIGN KEY (batch_id) REFERENCES medicine_batch (batch_id),
        CONSTRAINT chk_sale_item_quantity CHECK (quantity > 0),
        CONSTRAINT chk_sale_item_unit_price CHECK (unit_price >= 0)
    );

--- Payment Method
CREATE TABLE
    payment_method (
        payment_method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        method_name VARCHAR2 (50) NOT NULL,
        description VARCHAR2 (200),
        CONSTRAINT uk_payment_method_name UNIQUE (method_name)
    );

--- Payment
CREATE TABLE
    payment (
        payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_id NUMBER NOT NULL,
        payment_method_id NUMBER NOT NULL,
        amount NUMBER (10, 2) NOT NULL,
        payment_date DATE NOT NULL,
        payment_status VARCHAR2 (20) NOT NULL,
        CONSTRAINT fk_payment_sale FOREIGN KEY (sale_id) REFERENCES sale (sale_id),
        CONSTRAINT fk_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_method (payment_method_id),
        CONSTRAINT uk_payment_sale UNIQUE (sale_id),
        CONSTRAINT chk_payment_amount CHECK (amount >= 0),
        CONSTRAINT chk_payment_status CHECK (
            payment_status IN ('PAID', 'PENDING', 'FAILED', 'REFUNDED')
        )
    );

--- Stock Movement
CREATE TABLE
    stock_movement (
        movement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batch_id NUMBER NOT NULL,
        movement_type VARCHAR2 (20) NOT NULL,
        quantity NUMBER NOT NULL,
        movement_date DATE NOT NULL,
        reference_type VARCHAR2 (30),
        reference_id NUMBER,
        description VARCHAR2 (250),
        CONSTRAINT fk_stock_movement_batch FOREIGN KEY (batch_id) REFERENCES medicine_batch (batch_id),
        CONSTRAINT chk_stock_movement_type CHECK (
            movement_type IN ('IN', 'OUT', 'ADJUST', 'EXPIRED')
        ),
        CONSTRAINT chk_stock_movement_quantity CHECK (quantity > 0)
    );